### ISSUE TITLE
Wrong type conversion for concrete LatLon type

### ISSUE THREAD

**Issue by jrklasen** [JuliaEarth/CoordRefSystems.jl#120]
First of all, thanks for the great package!

I stumbled up on some strange behavior which I would like to report.

I would like to use the (Geodetic)LatLon type in my one work. As it is by default not concrete,

```
isconcretetype(LatLon)
```

I would like to specify it in the following way,

```
isconcretetype(LatLon{WGS84Latest,typeof(1.1u"°")})
# or
isconcretetype(LatLon{WGS84Latest,Deg{Float64}})
```

this woks if the inputs are Unitful,

```
LatLon{WGS84Latest,Deg{Float64}}(53.00u"°", 9.00u"°")
```

but yields wrong results if they are not

```
LatLon{WGS84Latest,Deg{Float64}}(53.00, 9.00)
LatLon{WGS84Latest,Deg{Float64}}(53, 9)
```

**Comment by ettersi** [comment]
I assume the unexpected behaviour is that plain-number input undergoes a radians to degree conversion?
```julia
julia> LatLon{WGS84Latest,Deg{Float64}}(53, 9)
GeodeticLatLon{WGS84Latest} coordinates
├─ lat: 3036.676314193363° # == 53 * 180 / π
└─ lon: 515.662015617741°
```

The reason for this is this conversion rule in Unitful: 
```julia
julia> convert(Deg{Float64}, 1)
57.29577951308232°
```

Unfortunately, there is not much CoordRefSystems can do about this. If you think this is confusing (and I would agree with you if you did), then I'm afraid you'd have to file an issue with Unitful instead. 

----

Having said this, can you give a bit more detail as to why you would like to call the fully parametrised constructor? CoordRefSystems / Julia will automatically default / infer any type parameter that you do not explicitly provide at zero runtime cost, so usually there is no reason to state these parameters explicitly. But of course, every use case is different, so the more we know about your use case the better we can help you.

**Comment by jrklasen** [comment]
Thanks for your swift reply

> CoordRefSystems / Julia will automatically default / infer any type parameter that you do not explicitly provide at zero runtime cost, so usually there is no reason to state these parameters explicitly.

I see, in this case I can define a fully parametrized LatLon within my struct and use the unspecified constructor for it.

**Comment by juliohm** [comment]
Thank you @ettersi 💯 

@jrklasen you can usually hide these type parameter details using another type parameter in your struct:

```julia
struct MyStruct{C<:CRS}
  coords::C
end
```

In this case `C` will materialize the concrete type that you need.

Please let us know if you need further assistance.

**Comment by ettersi** [comment]
> I see, in this case I can define a fully parametrized LatLon within my struct and use the unspecified constructor for it.

Correct. And if you ever need to convince yourself that the parameters are inferred the way that you intended, you can use `typeof`: 

```julia
julia> typeof(LatLon(53, 9))
GeodeticLatLon{WGS84Latest, Quantity{Float64, NoDims, Unitful.FreeUnits{(°,), NoDims, nothing}}}
```
