### ISSUE TITLE
Assess access traits for specific coordinate names

### ISSUE THREAD

**Issue by juliohm** [JuliaEarth/CoordRefSystems.jl#127]
As we start to work on specialized algorithms for various CRS, we observe this common access pattern:

```julia
coords = Cartesian(x, y, z)

lat(coords) = convert(LatLonAlt, coords).lat
```

We can probably add helper trait functions `lat`, `lon`, `x`, `y`, ... to be used as `CoordRefSystems.lat(coords)`.

**Comment by juliohm** [comment]
Thinking about this more carefully, we don't want to promote the usage of such functions because they require converting the CRS twice in most practical cases. For instance, if someone needs the `lat` and `lon`, it is more efficient to convert the CRS once, and access `coords.lat` and `coords.lon`.

**Comment by ettersi** [comment]
What about 
```julia
function latlonalt(coords)
    latlon = convert(LatLonAlt, coords)
    return (latlon.lat, latlon.lon, latlon.alt)
 end
```
so you can do
```julia
(lat, lon, alt) = latlonalt(some_coords)
```

**Comment by juliohm** [comment]
I believe it falls in the same issue where we could simply recommend the explicit `convert`. It is an extra line of code that makes things more transparent for readers.
