### ISSUE TITLE
Add support for EPSG:27700

### ISSUE THREAD

**Issue by TimG1964** [JuliaEarth/CoordRefSystems.jl#131]
```
ERROR: LoadError: ArgumentError: EPSG/ESRI code for the ESRI ID "British_National_Grid" not found in dictionary.
Please check https://github.com/JuliaEarth/CoordRefSystems.jl/blob/main/src/strings.jl
If you know the EPSG/ESRI code of a given ESRI WKT string, please submit a pull request.
```
I'm reading this shape file from [here](https://geoportal.statistics.gov.uk/datasets/127c4bda06314409a1fa0df505f510e6_0/explore) at the the UK Office for National Statistics (ONS): `LAD_DEC_2023_UK_BGC.shp`.
Google tells me the British National Grid is `EPSG:27700`.

**Comment by juliohm** [comment]
We added the code and corresponding type as discussed in https://discourse.julialang.org/t/esri-code-for-british-national-grid-not-known-by-geoio/117641

I will leave this issue open because we still need to work on a final missing feature to make conversions 100% correct.
