### ISSUE TITLE
Add support for MAGNA-SIGRAS EPSG:4686 

### ISSUE THREAD

**Issue by romu545** [JuliaEarth/CoordRefSystems.jl#153]
https://github.com/JuliaEarth/CoordRefSystems.jl/blob/main/src/strings.jl
If you know the EPSG/ESRI code of a given ESRI WKT string, please submit a pull request.

**Comment by juliohm** [comment]
Hi Rafael, please submit a pull request as the message says. Need help with
that?

Em sáb., 17 de ago. de 2024, 14:07, Rafael Mendoza Ureche <
***@***.***> escreveu:

**Comment by juliohm** [comment]
@romu545 check this page: https://epsg.io/4686

At the bottom you can find the option "Export ESRI WKT". Click on it to see the following string:

```
GEOGCS["GCS_MAGNA",
    DATUM["D_MAGNA",
        SPHEROID["GRS_1980",6378137.0,298.257222101]],
    PRIMEM["Greenwich",0.0],
    UNIT["Degree",0.0174532925199433]]
```
 
You need to map the ESRI string `"GCS_MAGNA"` to the `EPSG{4686}` code in the dictionary here;

https://github.com/JuliaEarth/CoordRefSystems.jl/blob/b342316c2315cb6b571b86399b6880f240bb3105/src/strings.jl#L72

Do you know how to submit a pull request on GitHub?

**Comment by romu545** [comment]
Hi!

I don't have the necessary experience to submit a pull request on GitHub
________________________________
De: Júlio Hoffimann ***@***.***>
Enviado: lunes, 19 de agosto de 2024 9:22 a. m.
Para: JuliaEarth/CoordRefSystems.jl ***@***.***>
Cc: Rafael Mendoza Ureche ***@***.***>; Mention ***@***.***>
Asunto: Re: [JuliaEarth/CoordRefSystems.jl] Add support for MAGNA-SIGRAS EPSG:4686 (Issue #153)


@romu545<https://github.com/romu545> check this page: https://epsg.io/4686

At the bottom you can find the option "Export ESRI WKT". Click on it to see the following string:

GEOGCS["GCS_MAGNA",
    DATUM["D_MAGNA",
        SPHEROID["GRS_1980",6378137.0,298.257222101]],
    PRIMEM["Greenwich",0.0],
    UNIT["Degree",0.0174532925199433]]


You need to map the ESRI string "GCS_MAGNA" to the EPSG{4686} code in the dictionary here;

https://github.com/JuliaEarth/CoordRefSystems.jl/blob/b342316c2315cb6b571b86399b6880f240bb3105/src/strings.jl#L72

Do you know how to submit a pull request on GitHub?

**Comment by juliohm** [comment]
No worries. Check this guide: https://github.com/firstcontributions/first-contributions

Try to follow those steps and ask for help here if you have questions.

**Comment by juliohm** [comment]
Thank you for fixing it @romu545.

For reference: #154

**Comment by juliohm** [comment]
A patch release has been triggered, should be available in 15min: https://github.com/JuliaRegistries/General/pull/113494
