### ISSUE TITLE
Add support for `EPSG:5070` and Albers projection

### ISSUE THREAD

**Issue by souma4** [JuliaEarth/CoordRefSystems.jl#183]
I was going to do some test analyses using GeoStats and found I could not load my test datasets because they used [EPSG:5070](https://epsg.org/crs_5070/NAD83-Conus-Albers.html?sessionkey=5z8h7yfi3y). This EPSG requires the Albers projection, which has not been developed yet. Yesterday I worked up a script and followed the instructions from [this thread](https://discourse.julialang.org/t/esri-code-for-british-national-grid-not-known-by-geoio/117641/13) to add EPSG 5070. I referenced mercator and transversemercator for the script I wrote, so I know the core functionality needed should be in the eqareaalbers.jl script I wrote. However, there may be changes to the algorithm/arguments that align more with your design philosophy.

If this is in line with the current intent for CoordRefSystems.jl I can submit a pull request and make final adjustments.

**Comment by juliohm** [comment]
Hi @souma4 , thank you for taking the time to experiment with the code. Please feel free to submit a pull request. We can help you with final adjustments to match the conventions in the project.

**Comment by juliohm** [comment]
Thank you @souma4 ❤️ 

Fixed on master.
