### ISSUE TITLE
Addition of a Spherical Ellipsoid

### ISSUE THREAD

**Issue by disberd** [JuliaEarth/CoordRefSystems.jl#98]
Hi,

In my field (satellite communications) it is often assumed for many simulations that the earth is just a sphere as it simplifies a lot of the computations and most of the time does not impact significantly the results.

While I do believe the simplification are not really meaningful when a proper and optimized implementation of the computation is in place (like in this ecosystem), it is still often the case that one has to simulate things with a spherical ellipsoid to reproduce results done by other with less powerful means :D.

Would you be willing to add a spherical ellipsoid (I was thinking with 6371km of radius as that is the [wikipedia](https://en.wikipedia.org/wiki/Earth_radius#:~:text=Approximating%20the%20figure%20of%20Earth,polar%20radius%2C%20denoted%20b) _average_ value), or do you think this is not meant for CoordRefSystem and should live in my private package?

I am fine with either but I believe it might be of use to someone else to have a common definition of the spherical ellipsoid living in this repository.

In case you'd be willing to have this here, what would be the most idiomatic way to define the corresponding Datum to use for the various coordinates? 
Would it still be fine to have something like `Spherical6371🌎` and just `Spherical6371` for the datum? (I assume simply `Spherical` is used already for the coordinates and even if its not it would be too generic for something so niche most likely)

**Comment by juliohm** [comment]
Hi @disberd ! Thanks for proposing improvements. Do you think you can find the datum you have in mind in the EPSG database? You can press the "Datums" tab in the following link: https://epsg.org/search/by-name

If the datum you have in mind is already in the database, we can try to adopt the exact same name here.

**Comment by disberd** [comment]
Hi @juliohm, thanks for the quick respons as always.
You'd have to bear with me as I am really not that experienced in datums, I just know they exists and assumed I needed to associate a specific datum to an ellipsoid for working with this package, so I do not have a specific in mind.

That being said, I could either find [this](https://epsg.org/datum_1360/NSIDC-International-1924-Authalic-Sphere.html?sessionkey=v875igr0ly) datum which seems to be associated to a spherical ellipsoid with around 6371km of radius.

Alternatively, i did find the GRS 1980 Authalic Sphere ellipsoid [here](https://epsg.io/7048-ellipsoid) which seems to be more generic, but could not easily find datums using it if not for [this](https://epsg.io/4047) one which seems deprecated.

For my intent and purposes the first datum/ellipsoid combination would most likely work as it has a spherical ellipsoid with almost the same radius as the GRS 1980 authalic sphere, (I say most likely just because as I said before I have no real understanding yet about datum implications...)

Would you have opinions/suggestions on either of the two combinations above?

**Comment by juliohm** [comment]
> You'd have to bear with me as I am really not that experienced in datums

Thanks for sharing. We are all learners :)

I believe we can implement a few improvements already:

1. We should consider adding a `GRS80S🌎` to represent the GRS 1980 Authalic Sphere. You can add it right below the `GRS80🌎` ellipsoid [here](https://github.com/JuliaEarth/CoordRefSystems.jl/blob/6cf31f4dd2cd37d73a6095f1142a816bca4d9b24/src/ellipsoids.jl#L127-L136) using the [ellipfromab](https://github.com/JuliaEarth/CoordRefSystems.jl/blob/6cf31f4dd2cd37d73a6095f1142a816bca4d9b24/src/utils.jl#L118-L130) helper function. You just need to pass the radius specified in the EPSG database, which will be equal to both axis of the ellipsoid (r = a = b).
2. Then, we can add a `GRS80S` datum [here](https://github.com/JuliaEarth/CoordRefSystems.jl/blob/main/src/datums.jl), which simply points to the added ellipsoid in the previous item.

You can repeat the two steps above for the NSIDC datum, by first adding the ellipsoid, and then the datum type. The datum is simply an ellipsoid with shape parameters plus a few other parameters that locate the origin of the coordinate system (e.g., Greenwhich longitude).

Pass the datum to any CRS type as a type parameter, and the constants will be used appropriately. For example `LatLon{GRS80S}` specifies the geodetic latitude and longitude of interest.

If you find other ellipsoids and datums useful, please feel free to submit pull requests. We can quickly review, merge and release a patch.
